Fix to delegate to properties
dhilst/delegate pull request #2
Opened 2020-01-17 20:19 UTC by valveca-ai

Fix for Issue #1

2020-01-19 13:44 UTC, dhilst requested changes
Thanks for the contribution and nice reuse of code

Can you update README stating that properties are handled too?

2020-01-19 22:29 UTC, valveca-ai commented
Updated README.

2020-01-20 03:39 UTC, dhilst approved these changes

2020-01-20 03:39 UTC, merged

2020-01-20 03:40 UTC, dhilst commented
Thanks for contributing :)